import { CameraView, useCameraPermissions } from 'expo-camera';
import { File } from 'expo-file-system';
import { ImageManipulator, SaveFormat } from 'expo-image-manipulator';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, BackHandler, Image, LayoutChangeEvent, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { predictImage } from '../api';
import { BoundingBoxOverlay } from '../components/BoundingBoxOverlay';
import { getResultCopy } from '../resultCopy';
import { colors } from '../theme';
import { Detection, Pipeline, PredictionResponse } from '../types';

type Picture={uri:string;width:number;height:number};
type ModelResult={pipeline:Pipeline;response:PredictionResponse;detections:Detection[];elapsedMs:number};
const MAX_SIDE=1600;
function remove(uri?:string){if(!uri)return;try{const file=new File(uri);if(file.exists)file.delete();}catch{}}
async function prepare(uri:string,width:number,height:number):Promise<Picture>{const context=ImageManipulator.manipulate(uri);if(Math.max(width,height)>MAX_SIDE){if(width>=height)context.resize({width:MAX_SIDE});else context.resize({height:MAX_SIDE});}const rendered=await context.renderAsync();const saved=await rendered.saveAsync({compress:.72,format:SaveFormat.JPEG});return{uri:saved.uri,width:rendered.width,height:rendered.height};}
function guideCandidates(items:Detection[],picture:Picture,view:{width:number;height:number}){if(!view.width||!view.height)return items;const scale=Math.max(view.width/picture.width,view.height/picture.height),ox=(view.width-picture.width*scale)/2,oy=(view.height-picture.height*scale)/2,left=view.width*.18,right=view.width*.82,top=view.height*.21,bottom=view.height*.80;return items.filter(item=>{const[x1,y1,x2,y2]=item.bbox,bl=ox+x1*scale,bt=oy+y1*scale,br=ox+x2*scale,bb=oy+y2*scale,cx=(bl+br)/2,cy=(bt+bb)/2,center=cx>=left&&cx<=right&&cy>=top&&cy<=bottom,iw=Math.max(0,Math.min(br,right)-Math.max(bl,left)),ih=Math.max(0,Math.min(bb,bottom)-Math.max(bt,top)),area=Math.max(1,(br-bl)*(bb-bt));return center||(iw*ih)/area>=.30;});}

export function ComparisonScreen({serverUrl,onBack}:{serverUrl:string;onBack:()=>void}){
  const camera=useRef<CameraView>(null),photoRef=useRef<Picture|null>(null);const insets=useSafeAreaInsets();const[permission,requestPermission]=useCameraPermissions();const[ready,setReady]=useState(false),[active,setActive]=useState(AppState.currentState==='active'),[busy,setBusy]=useState(false),[status,setStatus]=useState('같은 사진으로 두 모델을 비교해요'),[error,setError]=useState(''),[photo,setPhotoState]=useState<Picture|null>(null),[results,setResults]=useState<ModelResult[]>([]),[view,setView]=useState({width:0,height:0});
  const setPhoto=(p:Picture|null)=>{photoRef.current=p;setPhotoState(p);};
  const reset=useCallback(()=>{remove(photoRef.current?.uri);setPhoto(null);setResults([]);setError('');setStatus('같은 사진으로 두 모델을 비교해요');},[]);
  const back=useCallback(()=>{if(photoRef.current){reset();return;}onBack();},[onBack,reset]);
  useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{back();return true;});return()=>sub.remove();},[back]);
  useEffect(()=>{const sub=AppState.addEventListener('change',s=>setActive(s==='active'));return()=>sub.remove();},[]);
  useEffect(()=>()=>remove(photoRef.current?.uri),[]);
  const capture=async()=>{if(!camera.current||!ready||busy)return;setBusy(true);setError('');let originalUri:string|undefined;try{setStatus('사진을 준비하고 있어요…');const original=await camera.current.takePictureAsync({quality:.65,skipProcessing:false,shutterSound:false});if(!original)throw new Error('사진을 저장하지 못했습니다.');originalUri=original.uri;const prepared=await prepare(original.uri,original.width,original.height);remove(original.uri);originalUri=undefined;setPhoto(prepared);const output:ModelResult[]=[];for(const pipeline of ['one_stage','two_stage'] as Pipeline[]){setStatus(pipeline==='one_stage'?'1-stage 분석 중…':'2-stage 분석 중…');const start=Date.now();const response=await predictImage(serverUrl,prepared.uri,pipeline);const all=[...(response.detections||[])].sort((a,b)=>b.confidence-a.confidence);output.push({pipeline,response,detections:guideCandidates(all,prepared,view),elapsedMs:Date.now()-start});}setResults(output);setStatus('모델 비교 완료');}catch(e){if(originalUri)remove(originalUri);setError(e instanceof Error&&/[가-힣]/.test(e.message)?e.message:'모델 비교 중 오류가 발생했습니다.');setStatus('비교 오류');}finally{setBusy(false);}};
  if(!permission)return <Centered text="카메라 권한을 확인하고 있습니다…"/>;
  if(!permission.granted)return <View style={styles.center}><Text style={styles.title}>카메라 권한이 필요해요</Text><Pressable style={styles.button} onPress={requestPermission}><Text style={styles.buttonText}>권한 허용</Text></Pressable></View>;
  return <View style={styles.root}><View style={styles.top}><Pressable onPress={back}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.topTitle}>1·2-stage 모델 비교</Text><Text style={styles.topSub}>동일한 사진으로 결과 비교</Text></View><View style={{width:28}}/></View>
    {!photo?<View style={styles.cameraStage} onLayout={(e:LayoutChangeEvent)=>setView(e.nativeEvent.layout)}>{active?<><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back" onCameraReady={()=>setReady(true)}/><View pointerEvents="none" style={styles.guide}/><Text style={styles.guideText}>물체 중심을 가이드에 맞춰주세요</Text></>:<View style={styles.center}><Text style={styles.muted}>카메라가 일시정지됐어요</Text></View>}<View style={styles.status}><Text style={styles.statusText}>{status}</Text></View><Pressable style={[styles.shutter,!ready&&{opacity:.4}]} disabled={!ready||busy} onPress={()=>void capture()}><View style={styles.shutterInner}/></Pressable></View>:
    <ScrollView contentContainerStyle={[styles.resultContent,{paddingBottom:insets.bottom+24}]}><Text style={styles.statusResult}>{status}</Text>{busy&&<ActivityIndicator size="large" color={colors.green}/>} {error?<Text style={styles.error}>{error}</Text>:null}{results.length===2&&<><View style={styles.compareRow}>{results.map(result=><ResultCard key={result.pipeline} picture={photo} result={result}/>)}</View><View style={styles.table}>{results.map(result=><ResultSummary key={result.pipeline} result={result}/>)}</View></>}{!busy&&<Pressable style={styles.again} onPress={reset}><Text style={styles.buttonText}>다시 비교하기</Text></Pressable>}</ScrollView>}
  </View>;
}
function ResultCard({picture,result}:{picture:Picture;result:ModelResult}){const[layout,setLayout]=useState({width:0,height:0});const primary=result.detections[0];return <View style={styles.resultCard}><Text style={styles.modelName}>{result.pipeline==='one_stage'?'1-stage':'2-stage'}</Text><View style={styles.resultImage} onLayout={e=>setLayout(e.nativeEvent.layout)}><Image source={{uri:picture.uri}} style={StyleSheet.absoluteFill} resizeMode="contain"/><BoundingBoxOverlay detections={primary?[primary]:[]} imageWidth={picture.width} imageHeight={picture.height} viewWidth={layout.width} viewHeight={layout.height}/></View><Text style={styles.smallResult}>{primary?`${getResultCopy(primary).materialName} · ${getResultCopy(primary).conditionName}`:'탐지 결과 없음'}</Text></View>}
function ResultSummary({result}:{result:ModelResult}){const primary=result.detections[0],copy=primary?getResultCopy(primary):null;const modelTime=result.response.processing_time_ms??result.response.inference_time_ms??result.response.inference_ms;return <View style={styles.summary}><Text style={styles.summaryTitle}>{result.pipeline==='one_stage'?'1-stage':'2-stage'}</Text><Text style={styles.line}>재질: {copy?.materialName||'찾지 못함'}</Text><Text style={styles.line}>상태: {copy?.conditionName||'-'}</Text><Text style={styles.line}>신뢰도: {primary?`${Math.round(primary.confidence*100)}%`:'-'}</Text><Text style={styles.line}>후보: {result.detections.length}개</Text><Text style={styles.line}>모델 시간: {modelTime!=null?`${Math.round(modelTime)}ms`:'미제공'}</Text><Text style={styles.line}>앱 왕복: {result.elapsedMs}ms</Text></View>}
function Centered({text}:{text:string}){return <View style={styles.center}><ActivityIndicator color={colors.green}/><Text style={styles.muted}>{text}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.black},top:{height:70,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:colors.white,fontSize:36},topTitle:{color:colors.white,fontSize:17,fontWeight:'900',textAlign:'center'},topSub:{color:'#A8B3AD',fontSize:11,textAlign:'center',marginTop:3},cameraStage:{flex:1,overflow:'hidden'},guide:{position:'absolute',left:'18%',right:'18%',top:'21%',bottom:'20%',borderWidth:2,borderColor:colors.white,borderRadius:22},guideText:{position:'absolute',bottom:110,alignSelf:'center',backgroundColor:'rgba(0,0,0,.65)',color:colors.white,padding:8,borderRadius:12,fontSize:11},status:{position:'absolute',top:14,alignSelf:'center',backgroundColor:'rgba(0,0,0,.7)',paddingHorizontal:15,paddingVertical:9,borderRadius:18},statusText:{color:colors.white,fontWeight:'800'},shutter:{position:'absolute',bottom:24,width:72,height:72,borderRadius:36,borderWidth:4,borderColor:colors.white,left:'50%',marginLeft:-36,padding:5},shutterInner:{flex:1,borderRadius:30,backgroundColor:colors.green},resultContent:{backgroundColor:colors.pale,minHeight:'100%',padding:16},statusResult:{fontSize:20,fontWeight:'900',color:colors.ink,textAlign:'center',marginBottom:14},compareRow:{flexDirection:'row',gap:10},resultCard:{flex:1,backgroundColor:colors.white,borderRadius:15,padding:8},modelName:{fontWeight:'900',color:colors.greenDark,textAlign:'center',marginBottom:7},resultImage:{height:230,backgroundColor:colors.black,borderRadius:9,overflow:'hidden'},smallResult:{fontSize:11,fontWeight:'800',color:colors.ink,textAlign:'center',marginTop:8},table:{flexDirection:'row',gap:10,marginTop:12},summary:{flex:1,backgroundColor:colors.white,borderRadius:15,padding:12},summaryTitle:{fontWeight:'900',fontSize:16,color:colors.ink,marginBottom:7},line:{fontSize:11,color:colors.muted,lineHeight:19},again:{backgroundColor:colors.green,borderRadius:14,padding:15,alignItems:'center',marginTop:14},button:{backgroundColor:colors.green,borderRadius:14,paddingHorizontal:24,paddingVertical:13,marginTop:18},buttonText:{color:colors.white,fontWeight:'900'},center:{flex:1,backgroundColor:colors.pale,alignItems:'center',justifyContent:'center',padding:25},title:{fontSize:22,fontWeight:'900',color:colors.ink},muted:{color:colors.muted,marginTop:10},error:{color:colors.red,textAlign:'center',marginVertical:15}});
