import { useState } from 'react';
import { useEffect } from 'react';
import { BackHandler, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { guides } from '../data/guides'; import { colors } from '../theme'; import { MaterialId } from '../types';
export function GuideScreen({initialMaterial,onBack}:{initialMaterial:MaterialId;onBack:()=>void}){
  const [selected,setSelected]=useState(initialMaterial); const [expanded,setExpanded]=useState(false); const guide=guides.find(g=>g.id===selected)!;
  useEffect(()=>{const subscription=BackHandler.addEventListener('hardwareBackPress',()=>{onBack();return true;});return()=>subscription.remove();},[onBack]);
  const buttons=guides.map(g=><Pressable key={g.id} onPress={()=>setSelected(g.id)} style={[styles.chip,selected===g.id&&styles.chipOn]}><Text style={styles.chipIcon}>{g.icon}</Text><Text style={[styles.chipText,selected===g.id&&styles.chipTextOn]}>{g.name}</Text></Pressable>);
  return <ScrollView contentContainerStyle={styles.content}><Pressable onPress={onBack}><Text style={styles.back}>‹ 홈으로</Text></Pressable><Text style={styles.title}>무엇을 버리시나요?</Text><Text style={styles.sub}>재질을 선택하면 기본 배출 순서를 확인할 수 있어요.</Text>
    {expanded?<View style={styles.grid}>{buttons}</View>:<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontal}>{buttons}</ScrollView>}
    <Pressable onPress={()=>setExpanded(v=>!v)} style={styles.expand}><Text style={styles.expandText}>{expanded?'간단히 보기 ↑':'전체 재질 보기 ↓'}</Text></Pressable>
    <View style={styles.card}><Text style={styles.bigIcon}>{guide.icon}</Text><Text style={styles.name}>{guide.name}</Text><Text style={styles.summary}>{guide.summary}</Text>{guide.steps.map((step,i)=><View style={styles.step} key={step}><Text style={styles.number}>{i+1}</Text><Text style={styles.stepText}>{step}</Text></View>)}</View>
    <View style={styles.source}><Text style={styles.sourceTitle}>지역별 배출 기준을 확인해주세요</Text><Text style={styles.sourceText}>품목과 지역에 따라 배출 방식이 다를 수 있습니다. 실제 배출 전 거주 지역의 최신 분리배출 안내를 함께 확인해주세요.</Text></View>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:22,paddingBottom:45},back:{color:colors.green,fontWeight:'800',fontSize:16},title:{fontSize:29,fontWeight:'900',color:colors.ink,marginTop:18},sub:{color:colors.muted,marginTop:8,marginBottom:18},horizontal:{gap:9,paddingRight:20},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:15,padding:11,alignItems:'center',width:100},chipOn:{backgroundColor:colors.greenDark,borderColor:colors.greenDark},chipIcon:{fontSize:24},chipText:{color:colors.ink,fontSize:11,fontWeight:'700',marginTop:5},chipTextOn:{color:colors.white},expand:{alignItems:'center',padding:13},expandText:{color:colors.green,fontWeight:'800'},card:{backgroundColor:colors.white,borderRadius:24,padding:22,marginTop:6},bigIcon:{fontSize:48},name:{fontSize:25,fontWeight:'900',color:colors.ink,marginTop:8},summary:{color:colors.muted,fontSize:15,lineHeight:22,marginVertical:18},step:{flexDirection:'row',alignItems:'center',gap:12,borderTopColor:colors.line,borderTopWidth:1,paddingVertical:15},number:{backgroundColor:colors.mint,color:colors.greenDark,fontWeight:'900',width:29,height:29,borderRadius:15,textAlign:'center',lineHeight:29},stepText:{flex:1,color:colors.ink,lineHeight:21},source:{backgroundColor:'#FFF4DF',padding:15,borderRadius:15,marginTop:14},sourceTitle:{color:'#72511E',fontWeight:'900'},sourceText:{color:'#806A47',fontSize:12,lineHeight:18,marginTop:5}});
