import { useState } from 'react';
import { FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { guides } from '../data/guides';
import { colors } from '../theme';
import { AnalysisLog, CameraMode, MaterialId, Pipeline } from '../types';

type Props={ pipeline:Pipeline; onPipelineChange:(v:Pipeline)=>void; onOpenCamera:(m:CameraMode)=>void; onOpenHistory:()=>void; onOpenGuide:(m:MaterialId)=>void; logs:AnalysisLog[] };
export function HomeScreen({pipeline,onPipelineChange,onOpenCamera,onOpenHistory,onOpenGuide,logs}:Props){
  const[modelOpen,setModelOpen]=useState(false);
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Text style={styles.eyebrow}>RECYCLE VISION</Text><Text style={styles.title}>버리기 전에,{`\n`}AI에게 물어보세요</Text>
    <Text style={styles.desc}>카메라로 재활용품의 재질과 오염 상태를 확인하고 배출 방법을 안내받아보세요.</Text>
    <Pressable style={styles.hero} onPress={()=>setModelOpen(v=>!v)}>
      <Text style={styles.heroIcon}>⌁</Text><View style={{flex:1}}><Text style={styles.heroTitle}>AI 카메라 분석</Text><Text style={styles.modelLabel}>분석 모델</Text><Text style={styles.heroDesc}>{pipeline==='one_stage'?'1-stage · 빠른 통합 분석':'2-stage · 단계별 분석'}</Text></View><Text style={styles.heroArrow}>{modelOpen?'⌃':'⌄'}</Text>
    </Pressable>
    {modelOpen&&<View style={styles.modelMenu}><ModelOption active={pipeline==='one_stage'} title="1-stage · 빠른 통합 분석" desc="재질과 오염 상태를 한 번에 분류합니다." onPress={()=>{onPipelineChange('one_stage');setModelOpen(false);}}/><ModelOption active={pipeline==='two_stage'} title="2-stage · 단계별 분석" desc="재질 탐지 후 오염 상태를 별도로 분류합니다." onPress={()=>{onPipelineChange('two_stage');setModelOpen(false);}}/></View>}
    <View style={styles.row}><Pressable style={styles.primary} onPress={()=>onOpenCamera('manual')}><Text style={styles.primaryText}>● 수동 촬영</Text></Pressable><Pressable style={styles.secondary} onPress={()=>onOpenCamera('auto')}><Text style={styles.secondaryText}>◎ 자동 촬영</Text></Pressable></View>
    <Text style={styles.notice}>현재 캔·페트병·플라스틱을 지원합니다. 한 번에 한 물체를 촬영해주세요.</Text>
    <View style={styles.headingRow}><Text style={styles.sectionTitle}>무엇을 버리시나요?</Text><Text style={styles.count}>{guides.length}가지 안내</Text></View>
    {guides.map((g)=><Pressable key={g.id} style={styles.guide} onPress={()=>onOpenGuide(g.id)}><Text style={styles.guideIcon}>{g.icon}</Text><View style={{flex:1}}><Text style={styles.guideName}>{g.name}</Text><Text numberOfLines={1} style={styles.guideSummary}>{g.summary}</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}
    {logs.length>0&&<><View style={styles.historyHeading}><Text style={styles.sectionTitle}>최근 분석 {logs.length}</Text><Pressable onPress={onOpenHistory}><Text style={styles.historyLink}>전체 기록 보기 ›</Text></Pressable></View><FlatList horizontal data={logs.slice(0,8)} keyExtractor={(x)=>x.id} renderItem={({item})=><Pressable style={styles.log} onPress={onOpenHistory}><Image source={{uri:item.cropUri}} style={styles.logImage}/><Text numberOfLines={1} style={styles.logLabel}>{item.label}</Text><Text style={styles.logConfidence}>AI 확신도 {Math.round(item.confidence*100)}%</Text></Pressable>} /></>}
    <Text style={styles.footnote}>AI 분석 결과는 촬영 환경에 따라 달라질 수 있습니다. 실제 배출 기준은 지역별 안내를 함께 확인해주세요.</Text>
  </ScrollView>;
}
function ModelOption({active,title,desc,onPress}:{active:boolean;title:string;desc:string;onPress:()=>void}){return <Pressable style={[styles.modelOption,active&&styles.modelOptionOn]} onPress={onPress}><View style={{flex:1}}><Text style={[styles.modelTitle,active&&styles.modelTitleOn]}>{title}</Text><Text style={[styles.modelDesc,active&&styles.modelDescOn]}>{desc}</Text></View><Text style={[styles.modelCheck,active&&styles.modelTitleOn]}>{active?'✓':''}</Text></Pressable>}
const styles=StyleSheet.create({
  content:{padding:22,paddingBottom:50},eyebrow:{color:colors.green,fontWeight:'900',letterSpacing:2,fontSize:12},title:{fontSize:34,lineHeight:43,fontWeight:'900',color:colors.ink,marginTop:10},desc:{color:colors.muted,fontSize:15,lineHeight:23,marginVertical:16},hero:{backgroundColor:colors.greenDark,borderRadius:24,padding:20,flexDirection:'row',gap:14,alignItems:'center'},heroIcon:{fontSize:42,color:colors.white},heroTitle:{fontSize:20,fontWeight:'900',color:colors.white},modelLabel:{color:'#A9CDBB',fontSize:10,fontWeight:'800',marginTop:8},heroDesc:{color:colors.white,marginTop:2,lineHeight:19,fontWeight:'800'},heroArrow:{color:colors.white,fontSize:23},modelMenu:{backgroundColor:colors.white,borderRadius:18,padding:8,marginTop:8},modelOption:{padding:13,borderRadius:13,flexDirection:'row',alignItems:'center'},modelOptionOn:{backgroundColor:colors.mint},modelTitle:{fontWeight:'900',color:colors.ink},modelTitleOn:{color:colors.greenDark},modelDesc:{fontSize:11,color:colors.muted,marginTop:4},modelDescOn:{color:colors.green},modelCheck:{width:24,fontWeight:'900'},row:{flexDirection:'row',gap:10,marginTop:12},primary:{flex:1,backgroundColor:colors.green,borderRadius:15,paddingVertical:15,alignItems:'center'},primaryText:{color:colors.white,fontWeight:'800'},secondary:{flex:1,backgroundColor:colors.white,borderColor:colors.green,borderWidth:1.5,borderRadius:15,paddingVertical:15,alignItems:'center'},secondaryText:{color:colors.greenDark,fontWeight:'800'},notice:{backgroundColor:'#FFF4DF',color:'#7D5B21',padding:12,borderRadius:12,marginTop:10,fontSize:12,lineHeight:18},sectionTitle:{fontSize:19,fontWeight:'900',color:colors.ink},headingRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:26,marginBottom:10},count:{color:colors.muted,fontSize:12},guide:{backgroundColor:colors.white,borderRadius:16,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',gap:12},guideIcon:{fontSize:27},guideName:{fontWeight:'800',color:colors.ink,fontSize:16},guideSummary:{color:colors.muted,marginTop:3,fontSize:12},arrow:{fontSize:28,color:colors.green},historyHeading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:24},historyLink:{color:colors.green,fontWeight:'900',fontSize:12},log:{backgroundColor:colors.mint,padding:9,borderRadius:12,marginTop:10,marginRight:8,width:126},logImage:{width:108,height:76,borderRadius:8,backgroundColor:colors.line},logMode:{fontSize:10,color:colors.green,marginTop:7},logLabel:{fontWeight:'800',marginTop:3},logConfidence:{color:colors.muted,fontSize:12},footnote:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:26},
});
